### ISSUE TITLE
Fabric version?

### ISSUE THREAD

**Issue by NatoBoram** [ate47/Xray#15]
Hi! I noticed that the mod went from Fabric 1.15.2 to Forge 1.16.5. Are there any plans to bring back Fabric support?

**Comment by loonybtard** [comment]
Hi! For clarity, I should note that the previous developer(ate47) has problems updating this mod.  So now I am maintaining this project.

About your question. In the original version of the issue, there was nothing about "Fabric". Therefore, I sincerely believed that is about "Forge".  Since the Fabric version is so popular, I don't see any reason to stop supporting it. But I'll need a little time. About a week, i think

**Comment by NatoBoram** [comment]
Yeah, I should've specified the API I wanted when I raised #12, my bad 😄

At the time, the latest versions were Fabric 1.15.2 + Forge 1.15.2, so I didn't think much about it
